# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 1061)
        MainWindow.setStyleSheet("font-size: 20px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.display3d = QtWidgets.QWidget()
        self.display3d.setObjectName("display3d")
        self.image3dLayout = QtWidgets.QVBoxLayout(self.display3d)
        self.image3dLayout.setContentsMargins(0, 0, 0, 0)
        self.image3dLayout.setSpacing(0)
        self.image3dLayout.setObjectName("image3dLayout")
        self.stackedWidget.addWidget(self.display3d)
        self.displayGraphic = QtWidgets.QWidget()
        self.displayGraphic.setObjectName("displayGraphic")
        self.imageGraphicLayout = QtWidgets.QVBoxLayout(self.displayGraphic)
        self.imageGraphicLayout.setContentsMargins(0, 0, 0, 0)
        self.imageGraphicLayout.setSpacing(0)
        self.imageGraphicLayout.setObjectName("imageGraphicLayout")
        self.stackedWidget.addWidget(self.displayGraphic)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar_1 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_1.setEnabled(True)
        self.toolBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar_1.setIconSize(QtCore.QSize(60, 60))
        self.toolBar_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar_1.setObjectName("toolBar_1")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_1)
        self.actionExit = QtWidgets.QAction(MainWindow)
        exit_icon = QtGui.QIcon()
        exit_icon.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/power.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionExit.setIcon(exit_icon)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.toolBar_1.addAction(self.actionExit)
        self.actionExit.triggered.connect(QtWidgets.qApp.quit)
        self.dockReportHeader = QtWidgets.QDockWidget(MainWindow)
        self.dockReportHeader.setMinimumSize(QtCore.QSize(200, 100))
        self.dockReportHeader.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockReportHeader.setObjectName("dockReportHeader")
        self.dockReportHeaderWidgetContents = QtWidgets.QWidget()
        self.dockReportHeaderWidgetContents.setObjectName(
            "dockReportHeaderWidgetContents"
        )
        self.LayoutReportHeader = QtWidgets.QVBoxLayout(
            self.dockReportHeaderWidgetContents
        )
        self.LayoutReportHeader.setObjectName("LayoutReportHeader")
        self.dockReportHeader.setWidget(self.dockReportHeaderWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockReportHeader)
        self.dockReportHeader2 = QtWidgets.QDockWidget(MainWindow)
        self.dockReportHeader2.setMinimumSize(QtCore.QSize(200, 100))
        self.dockReportHeader2.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockReportHeader2.setObjectName("dockReportHeader2")
        self.dockReportHeader2WidgetContents = QtWidgets.QWidget()
        self.dockReportHeader2WidgetContents.setObjectName(
            "dockReportHeader2WidgetContents"
        )
        self.LayoutReportHeader2 = QtWidgets.QVBoxLayout(
            self.dockReportHeader2WidgetContents
        )
        self.LayoutReportHeader2.setObjectName("LayoutReportHeader2")
        self.dockReportHeader2.setWidget(self.dockReportHeader2WidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockReportHeader2)
        self.dockHierarchyReport = QtWidgets.QDockWidget(MainWindow)
        self.dockHierarchyReport.setFeatures(
            QtWidgets.QDockWidget.AllDockWidgetFeatures
        )
        self.dockHierarchyReport.setObjectName("dockHierarchyReport")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setStyleSheet("")
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.LayoutHierarchyReport = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.LayoutHierarchyReport.setContentsMargins(0, 0, 0, 0)
        self.LayoutHierarchyReport.setSpacing(0)
        self.LayoutHierarchyReport.setObjectName("LayoutHierarchyReport")
        self.treeViewReport = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeViewReport.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeViewReport.setObjectName("treeViewReport")
        self.LayoutHierarchyReport.addWidget(self.treeViewReport)
        self.dockHierarchyReport.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockHierarchyReport)
        self.dockHierarchy = QtWidgets.QDockWidget(MainWindow)
        self.dockHierarchy.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockHierarchy.setObjectName("dockHierarchy")
        self.dockWidgetContents1 = QtWidgets.QWidget()
        self.dockWidgetContents1.setStyleSheet("")
        self.dockWidgetContents1.setObjectName("dockWidgetContents1")
        self.LayoutHierarchy = QtWidgets.QVBoxLayout(self.dockWidgetContents1)
        self.LayoutHierarchy.setContentsMargins(0, 0, 0, 0)
        self.LayoutHierarchy.setSpacing(0)
        self.LayoutHierarchy.setObjectName("LayoutHierarchy")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents1)
        self.treeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeView.setObjectName("treeView")
        self.LayoutHierarchy.addWidget(self.treeView)
        self.dockHierarchy.setWidget(self.dockWidgetContents1)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockHierarchy)
        self.dockProperties = QtWidgets.QDockWidget(MainWindow)
        self.dockProperties.setMinimumSize(QtCore.QSize(200, 58))
        self.dockProperties.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockProperties.setObjectName("dockProperties")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.LayoutProperties = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.LayoutProperties.setContentsMargins(0, 0, 0, 0)
        self.LayoutProperties.setSpacing(0)
        self.LayoutProperties.setObjectName("LayoutProperties")
        self.labelProperties = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.labelProperties.setText("")
        self.labelProperties.setObjectName("labelProperties")
        self.LayoutProperties.addWidget(self.labelProperties)
        self.dockProperties.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockProperties)
        self.dockTransform = QtWidgets.QDockWidget(MainWindow)
        self.dockTransform.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockTransform.setObjectName("dockTransform")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.LayoutTransform = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.LayoutTransform.setObjectName("LayoutTransform")
        self.dockTransform.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockTransform)
        self.dockEdit = QtWidgets.QDockWidget(MainWindow)
        self.dockEdit.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockEdit.setObjectName("dockEdit")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.LayoutEdit = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.LayoutEdit.setObjectName("LayoutEdit")
        self.dockEdit.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockEdit)
        self.dockReport = QtWidgets.QDockWidget(MainWindow)
        self.dockReport.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockReport.setObjectName("dockReport")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.LayoutReport = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.LayoutReport.setObjectName("LayoutReport")
        self.dockReport.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockReport)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setIconSize(QtCore.QSize(60, 60))
        self.toolBar_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.dockReportMain = QtWidgets.QDockWidget(MainWindow)
        self.dockReportMain.setObjectName("dockReportMain")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.LayoutReportMain = QtWidgets.QVBoxLayout(self.dockWidgetContents_8)
        self.LayoutReportMain.setObjectName("LayoutReportMain")
        self.dockReportMain.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockReportMain)
        self.dockClassify = QtWidgets.QDockWidget(MainWindow)
        self.dockClassify.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockClassify.setObjectName("dockClassify")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.LayoutClassify = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.LayoutClassify.setObjectName("LayoutClassify")
        self.dockClassify.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockClassify)
        self.dockDetector = QtWidgets.QDockWidget(MainWindow)
        self.dockDetector.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockDetector.setObjectName("dockDetector")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.LayoutDetector = QtWidgets.QVBoxLayout(self.dockWidgetContents_7)
        self.LayoutDetector.setObjectName("LayoutDetector")
        self.dockDetector.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockDetector)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setIconSize(QtCore.QSize(60, 60))
        self.toolBar_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_4.setMovable(False)
        self.toolBar_4.setAllowedAreas(
            QtCore.Qt.RightToolBarArea | QtCore.Qt.TopToolBarArea
        )
        self.toolBar_4.setIconSize(QtCore.QSize(60, 60))
        self.toolBar_4.setFloatable(False)
        self.toolBar_4.setObjectName("toolBar_4")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_4)
        self.dockGenerator = QtWidgets.QDockWidget(MainWindow)
        self.dockGenerator.setObjectName("dockGenerator")
        self.dockWidgetContents_81 = QtWidgets.QWidget()
        self.dockWidgetContents_81.setObjectName("dockWidgetContents_81")
        self.LayoutGenerator = QtWidgets.QVBoxLayout(self.dockWidgetContents_81)
        self.LayoutGenerator.setObjectName("LayoutGenerator")
        self.dockGenerator.setWidget(self.dockWidgetContents_81)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockGenerator)
        self.dockTracker = QtWidgets.QDockWidget(MainWindow)
        self.dockTracker.setObjectName("dockTracker")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.LayoutTracker = QtWidgets.QVBoxLayout(self.dockWidgetContents_9)
        self.LayoutTracker.setObjectName("LayoutTracker")
        self.dockTracker.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockTracker)
        self.dockReconstructor = QtWidgets.QDockWidget(MainWindow)
        self.dockReconstructor.setObjectName("dockReconstructor")
        self.dockWidgetContents_10 = QtWidgets.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.LayoutReconstructor = QtWidgets.QVBoxLayout(self.dockWidgetContents_10)
        self.LayoutReconstructor.setObjectName("LayoutReconstructor")
        self.dockReconstructor.setWidget(self.dockWidgetContents_10)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockReconstructor)
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/folder.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionOpen_Folder.setIcon(icon)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionReset = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/refresh.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionReset.setIcon(icon1)
        self.actionReset.setObjectName("actionReset")
        self.actionClassify = QtWidgets.QAction(MainWindow)
        self.actionClassify.setCheckable(True)
        self.actionClassify.setChecked(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/layers.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionClassify.setIcon(icon2)
        self.actionClassify.setObjectName("actionClassify")
        self.actionTransform = QtWidgets.QAction(MainWindow)
        self.actionTransform.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/contrast.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionTransform.setIcon(icon3)
        self.actionTransform.setObjectName("actionTransform")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/edit.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionEdit.setIcon(icon4)
        self.actionEdit.setObjectName("actionEdit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/save.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/download.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionExport.setIcon(icon6)
        self.actionExport.setObjectName("actionExport")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/feed.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionReport.setIcon(icon7)
        self.actionReport.setObjectName("actionReport")
        self.actionDetector = QtWidgets.QAction(MainWindow)
        self.actionDetector.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/Icons/maximise.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionDetector.setIcon(icon8)
        self.actionDetector.setObjectName("actionDetector")
        self.actionTracking = QtWidgets.QAction(MainWindow)
        self.actionTracking.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/NewIcons/Tracking.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionTracking.setIcon(icon9)
        self.actionTracking.setObjectName("actionTracking")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/NewIcons/Generative.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionGenerate.setIcon(icon10)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionReconstruct = QtWidgets.QAction(MainWindow)
        self.actionReconstruct.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/Icons/Resources/NewIcons/Reconstruction.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.actionReconstruct.setIcon(icon11)
        self.actionReconstruct.setObjectName("actionReconstruct")
        self.toolBar_1.addAction(self.actionOpen_Folder)
        self.toolBar_1.addSeparator()
        self.toolBar_1.addAction(self.actionReset)
        self.toolBar_1.addAction(self.actionTransform)
        self.toolBar_1.addAction(self.actionEdit)
        self.toolBar_2.addAction(self.actionReport)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionExport)
        self.toolBar_3.addAction(self.actionClassify)
        self.toolBar_3.addAction(self.actionDetector)
        self.toolBar_3.addAction(self.actionTracking)
        self.toolBar_3.addAction(self.actionGenerate)
        self.toolBar_3.addAction(self.actionReconstruct)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar_1.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockReportHeader.setWindowTitle(
            _translate("MainWindow", "Select Hospital")
        )
        self.dockReportHeader2.setWindowTitle(_translate("MainWindow", "Sort By"))
        self.dockHierarchyReport.setWindowTitle(_translate("MainWindow", "Hierarchy"))
        self.dockHierarchy.setWindowTitle(_translate("MainWindow", "Hierarchy"))
        self.dockProperties.setWindowTitle(_translate("MainWindow", "Properties"))
        self.dockTransform.setWindowTitle(_translate("MainWindow", "Transform"))
        self.dockEdit.setWindowTitle(_translate("MainWindow", "Edit"))
        self.dockReport.setWindowTitle(_translate("MainWindow", "Report"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.dockReportMain.setWindowTitle(_translate("MainWindow", "Report Image"))
        self.dockClassify.setWindowTitle(_translate("MainWindow", "Classify"))
        self.dockDetector.setWindowTitle(_translate("MainWindow", "Detector"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.toolBar_4.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockGenerator.setWindowTitle(_translate("MainWindow", "Generator"))
        self.dockTracker.setWindowTitle(_translate("MainWindow", "Tracker"))
        self.dockReconstructor.setWindowTitle(_translate("MainWindow", "Reconstructor"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open"))
        self.actionOpen_Folder.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionClassify.setText(_translate("MainWindow", "LandMark"))
        self.actionTransform.setText(_translate("MainWindow", "Transform"))
        self.actionTransform.setToolTip(_translate("MainWindow", "Transform"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionEdit.setToolTip(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Dicom"))
        self.actionExport.setToolTip(_translate("MainWindow", "Export"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionReport.setToolTip(_translate("MainWindow", "Report"))
        self.actionDetector.setText(_translate("MainWindow", "Abnormal"))
        self.actionDetector.setToolTip(_translate("MainWindow", "Detector"))
        self.actionTracking.setText(_translate("MainWindow", "Tracking"))
        self.actionTracking.setToolTip(_translate("MainWindow", "Tracking"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate"))
        self.actionGenerate.setToolTip(_translate("MainWindow", "Generate"))
        self.actionReconstruct.setText(_translate("MainWindow", "Reconstruct"))
        self.actionReconstruct.setToolTip(_translate("MainWindow", "Reconstruct"))


import resources_rc
