# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classify.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Classify(object):
    def setupUi(self, Classify):
        Classify.setObjectName("Classify")
        Classify.resize(400, 426)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Classify.sizePolicy().hasHeightForWidth())
        Classify.setSizePolicy(sizePolicy)
        self.classifyLayout = QtWidgets.QVBoxLayout(Classify)
        self.classifyLayout.setObjectName("classifyLayout")
        self.btn_executeAll = QtWidgets.QPushButton(Classify)
        self.btn_executeAll.setObjectName("btn_executeAll")
        self.classifyLayout.addWidget(self.btn_executeAll)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Classify)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.classifyResult = QtWidgets.QLineEdit(Classify)
        self.classifyResult.setObjectName("classifyResult")
        self.horizontalLayout_2.addWidget(self.classifyResult)
        self.classifyLayout.addLayout(self.horizontalLayout_2)
        self.classifyDisplay = QtWidgets.QLabel(Classify)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyDisplay.sizePolicy().hasHeightForWidth())
        self.classifyDisplay.setSizePolicy(sizePolicy)
        self.classifyDisplay.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.classifyDisplay.setLineWidth(2)
        self.classifyDisplay.setText("")
        self.classifyDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.classifyDisplay.setObjectName("classifyDisplay")
        self.classifyLayout.addWidget(self.classifyDisplay)

        self.retranslateUi(Classify)
        QtCore.QMetaObject.connectSlotsByName(Classify)

    def retranslateUi(self, Classify):
        _translate = QtCore.QCoreApplication.translate
        Classify.setWindowTitle(_translate("Classify", "Form"))
        self.btn_executeAll.setText(_translate("Classify", "Execute All"))
        self.label_2.setText(_translate("Classify", "Result"))
