# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detector.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detector(object):
    def setupUi(self, Detector):
        Detector.setObjectName("Detector")
        Detector.resize(465, 424)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Detector.sizePolicy().hasHeightForWidth())
        Detector.setSizePolicy(sizePolicy)
        self.detectorLayout = QtWidgets.QVBoxLayout(Detector)
        self.detectorLayout.setObjectName("detectorLayout")
        self.cb_displaySegmentation = QtWidgets.QCheckBox(Detector)
        self.cb_displaySegmentation.setObjectName("cb_displaySegmentation")
        self.detectorLayout.addWidget(self.cb_displaySegmentation)
        self.btn_executeAll = QtWidgets.QPushButton(Detector)
        self.btn_executeAll.setObjectName("btn_executeAll")
        self.detectorLayout.addWidget(self.btn_executeAll)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Detector)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.detectorResult = QtWidgets.QLineEdit(Detector)
        self.detectorResult.setObjectName("detectorResult")
        self.horizontalLayout_2.addWidget(self.detectorResult)
        self.detectorLayout.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(Detector)
        self.listWidget.setObjectName("listWidget")
        self.detectorLayout.addWidget(self.listWidget)

        self.retranslateUi(Detector)
        QtCore.QMetaObject.connectSlotsByName(Detector)

    def retranslateUi(self, Detector):
        _translate = QtCore.QCoreApplication.translate
        Detector.setWindowTitle(_translate("Detector", "Form"))
        self.cb_displaySegmentation.setText(_translate("Detector", "Display Segmentation"))
        self.btn_executeAll.setText(_translate("Detector", "Execute All"))
        self.label_2.setText(_translate("Detector", "Num lesion"))
