# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Generator(object):
    def setupUi(self, Generator):
        Generator.setObjectName("Generator")
        Generator.resize(423, 452)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Generator.sizePolicy().hasHeightForWidth())
        Generator.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Generator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Generator)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbb_lightMode = QtWidgets.QComboBox(Generator)
        self.cbb_lightMode.setObjectName("cbb_lightMode")
        self.cbb_lightMode.addItem("")
        self.cbb_lightMode.addItem("")
        self.horizontalLayout.addWidget(self.cbb_lightMode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.generateLayout = QtWidgets.QVBoxLayout()
        self.generateLayout.setObjectName("generateLayout")
        self.verticalLayout.addLayout(self.generateLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Generator)
        QtCore.QMetaObject.connectSlotsByName(Generator)

    def retranslateUi(self, Generator):
        _translate = QtCore.QCoreApplication.translate
        Generator.setWindowTitle(_translate("Generator", "Form"))
        self.label.setText(_translate("Generator", "Light mode"))
        self.cbb_lightMode.setItemText(0, _translate("Generator", "FICE"))
        self.cbb_lightMode.setItemText(1, _translate("Generator", "LCI"))
