# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelBrowser(object):
    def setupUi(self, ModelBrowser):
        ModelBrowser.setObjectName("ModelBrowser")
        ModelBrowser.resize(400, 147)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModelBrowser.sizePolicy().hasHeightForWidth())
        ModelBrowser.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModelBrowser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(ModelBrowser)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelPath = QtWidgets.QLineEdit(ModelBrowser)
        self.modelPath.setObjectName("modelPath")
        self.horizontalLayout.addWidget(self.modelPath)
        self.btn_browse = QtWidgets.QPushButton(ModelBrowser)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout.addWidget(self.btn_browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.btn_execute = QtWidgets.QPushButton(ModelBrowser)
        self.btn_execute.setObjectName("btn_execute")
        self.verticalLayout.addWidget(self.btn_execute)

        self.retranslateUi(ModelBrowser)
        QtCore.QMetaObject.connectSlotsByName(ModelBrowser)

    def retranslateUi(self, ModelBrowser):
        _translate = QtCore.QCoreApplication.translate
        ModelBrowser.setWindowTitle(_translate("ModelBrowser", "Form"))
        self.label.setText(_translate("ModelBrowser", "Model path"))
        self.btn_browse.setText(_translate("ModelBrowser", "Browse"))
        self.btn_execute.setText(_translate("ModelBrowser", "Execute"))
