# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\reportSort.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportSort(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1340, 849)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1481, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sortByName = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sortByName.setObjectName("sortByName")
        self.verticalLayout.addWidget(self.sortByName)
        self.sortByDate = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sortByDate.setObjectName("sortByDate")
        self.verticalLayout.addWidget(self.sortByDate)
        self.sortBySize = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sortBySize.setObjectName("sortBySize")
        self.verticalLayout.addWidget(self.sortBySize)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sortByName.setText(_translate("Form", "Name"))
        self.sortByDate.setText(_translate("Form", "Date"))
        self.sortBySize.setText(_translate("Form", "Size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
