# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1340, 849)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1481, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonHoangLong = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonHoangLong.setFont(font)
        self.buttonHoangLong.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonHoangLong.setObjectName("buttonHoangLong")
        self.verticalLayout.addWidget(self.buttonHoangLong)
        self.buttonBHDHY = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBHDHY.setFont(font)
        self.buttonBHDHY.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBHDHY.setObjectName("buttonBHDHY")
        self.verticalLayout.addWidget(self.buttonBHDHY)
        self.buttonHaiDuong = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonHaiDuong.setFont(font)
        self.buttonHaiDuong.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonHaiDuong.setObjectName("buttonHaiDuong")
        self.verticalLayout.addWidget(self.buttonHaiDuong)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonHoangLong.setText(_translate("Form", "Phong Kham HL"))
        self.buttonBHDHY.setText(_translate("Form", "Benh Vien DH Y"))
        self.buttonHaiDuong.setText(_translate("Form", "BV Dai Hoc Y Te Ky thuat HD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
